services:
  db:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: Afpa1234
    # volumes:
      # - ./data:/var/lib/mysql
    # ports:
      # - 3307:3306

  web:
    build: .
    ports:
      - 80:80
    volumes:
      - .:/var/www